# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stravastats < Formula
  desc ""
  homepage "https://github.com/tunaitis/homebrew-tools"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tunaitis/stravastats/releases/download/v0.1.0/stravastats_Darwin_arm64.tar.gz"
      sha256 "50a27aeb5fe44f35d19d0198fe3097fb094fda465f43da0dbe1b61da01558a41"

      def install
        bin.install "stravastats"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tunaitis/stravastats/releases/download/v0.1.0/stravastats_Darwin_x86_64.tar.gz"
      sha256 "557b9ab8415b223a4743d22080190cc6e081fbf36945f762ff387ba679c5617a"

      def install
        bin.install "stravastats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tunaitis/stravastats/releases/download/v0.1.0/stravastats_Linux_arm64.tar.gz"
      sha256 "152e2320ef7d77db69d346366c2952e4e6ec88a1138e71ddd5cb7802acf3a97a"

      def install
        bin.install "stravastats"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tunaitis/stravastats/releases/download/v0.1.0/stravastats_Linux_x86_64.tar.gz"
      sha256 "d6a8a25c3f30b82f7da7a1e119ac155e597f8756a7a7ac91b454b4058ec043e7"

      def install
        bin.install "stravastats"
      end
    end
  end
end
