# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timediff < Formula
  desc ""
  homepage "https://github.com/tunaitis/homebrew-tools"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tunaitis/timediff/releases/download/v0.2.0/timediff_Darwin_arm64.tar.gz"
      sha256 "d1c6c98f906ff979ebc715d34fbbdc3b5affb7f6d7e406b7f16af42418bbc6ce"

      def install
        bin.install "timediff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tunaitis/timediff/releases/download/v0.2.0/timediff_Darwin_x86_64.tar.gz"
      sha256 "08d9b045d3f7fe6182d73aa745519b9ba3cdca780b8766c8a914ddff9fda4688"

      def install
        bin.install "timediff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tunaitis/timediff/releases/download/v0.2.0/timediff_Linux_arm64.tar.gz"
      sha256 "7c5f4cf9d96908db531646d4622b5a581297c8c3282d48d722d26ff38f3d147d"

      def install
        bin.install "timediff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tunaitis/timediff/releases/download/v0.2.0/timediff_Linux_x86_64.tar.gz"
      sha256 "291841579a4694af1f932b02f828d73621bb719766038b7de014a188fb144a81"

      def install
        bin.install "timediff"
      end
    end
  end
end
