# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timediff < Formula
  desc ""
  homepage "https://github.com/tunaitis/homebrew-tools"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tunaitis/timediff/releases/download/v0.1.3/timediff_Darwin_arm64.tar.gz"
      sha256 "6b282cdff87c85842374dc51ece4cec0ccf63976cc2d32cd900f18b9cbe7ef55"

      def install
        bin.install "timediff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tunaitis/timediff/releases/download/v0.1.3/timediff_Darwin_x86_64.tar.gz"
      sha256 "ec8e45277bef440ab2b8db59f8142e4357a05f8780b8b437fcfef3895577b4ba"

      def install
        bin.install "timediff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tunaitis/timediff/releases/download/v0.1.3/timediff_Linux_x86_64.tar.gz"
      sha256 "97aaa3c4def074d79fb7ad70147daabcebbd887f8cea30d97f0de9ab8fd84e2f"

      def install
        bin.install "timediff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tunaitis/timediff/releases/download/v0.1.3/timediff_Linux_arm64.tar.gz"
      sha256 "2258d65a78a5d314e89e2eab2200d9ecc5f3349cdbf10fc11369ce6fb8e392de"

      def install
        bin.install "timediff"
      end
    end
  end
end
